name: luis
description: Microsoft Luis wrapper.
version: 0.0.1
#homepage: https://www.example.com
author: S.-C. Lee <consoledir@outlook.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: any

dev_dependencies:
  test: ^0.12.0